runtime: php
env: flex

runtime_config:
  document_root: public
  skip_lockdown_document_root: true

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:W1S8tu79IcJDqrBgV0983w4oTpQV9wWUPLjza4PhECo=
  STORAGE_DIR: /tmp
  APP_DEBUG: true

  CACHE_DRIVER: file
  SESSION_DRIVER: file
  
  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.googlemail.com
  MAIL_PORT: 465
  MAIL_USERNAME: lijq333@gmail.com
  MAIL_PASSWORD: 1q3e5tab
  MAIL_ENCRYPTION: ssl
  MAIL_FROM_ADDRESS: admin@teamten.com
  MAIL_FROM_NAME: TeamTen

  JWT_SECRET: y5c3PjWWYf2czAxFjDChefeZd7zRmgpp

  NEXMO_API_KEY: 9fffbcad
  NEXMO_API_SECRET: hBtcmVM7JgEmOpwc

  BUGSNAG_API_KEY: 9ee055d7d91335afdfefd7e8cdedbefb

  FACEBOOK_PAGE_ID: 342236433072588
  FACEBOOK_CLIENT_ID: 610989759339386
  FACEBOOK_CLIENT_SECRET: 9900d6676b7faad607a63cdb60518f14
  FACEBOOK_ACCESS_TOKEN: EAAIrsSORG3oBAFlRZANTDB8svZB9naEZCNehPLJBkxUbQ20S1FhGIbb17k48vHZCPIOylTWb3w9hqTbhfDZBfCZCKkjlLYZBElPJmVuNcWyGq56vlNfEv0qz9q4M9ZAMZAn0p49mxxEGFOLBbcBJKxx9GieYsKqFz4KZA9odMTsHNzAgZDZD

  TWITTER_CONSUMER_KEY: iXYAoYkQGLdo9JSgwlr64fLRM
  TWITTER_CONSUMER_SECRET: lJWnl50ue4ui11qVhDLD3q5S3E5hpH3wMbePr4LCDkzUJALU02
  TWITTER_ACCESS_TOKEN: 1105731297719148544-aTlPLd5a4CzwChJaTx8XWwOGoue7lx
  TWITTER_ACCESS_TOKEN_SECRET: mXrtEd5DHHkTr9u3EPDns8KNsK9AXeHW1eIrW8LhUJqw6

  GOOGLE_API_KEY: AIzaSyBYky3Q0f3bK8kZiN6LgvE97Np2Az1jdUg

  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_DATABASE: ssad
  DB_USERNAME: root
  DB_PASSWORD: HfPwsztd3D7cwltv
  DB_SOCKET: "/cloudsql/teamten:us-central1-a:ssad1"

beta_settings:
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "teamten:us-central1-a:ssad1"
